site_name: "Sigil Campaign Wiki"
site_url: "https://backstabbery-git.github.io/SigilCampaign/"

theme:
    name: torillic
    background_image: 'https://www.transparenttextures.com/patterns/parchment.png'

