name: Publish MkDocs via GitHub Pages
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          
      - name: Install and Build MkDocs
        run: |
          python -m pip install --upgrade pip
          python -m pip install mkdocs-material mkdocs-torillic mkdocs-roamlinks-plugin
          python -m mkdocs gh-deploy --force
